//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volumey.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Volumey.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_Diff {
            get {
                return ResourceManager.GetString("Error_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_F12 {
            get {
                return ResourceManager.GetString("Error_F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_HotkeyExists {
            get {
                return ResourceManager.GetString("Error_HotkeyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_NoDevice {
            get {
                return ResourceManager.GetString("Error_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_OpenReg {
            get {
                return ResourceManager.GetString("Error_OpenReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error_VolumeReg {
            get {
                return ResourceManager.GetString("Error_VolumeReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notification_Later {
            get {
                return ResourceManager.GetString("Notification_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notification_No {
            get {
                return ResourceManager.GetString("Notification_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notification_Yes {
            get {
                return ResourceManager.GetString("Notification_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NotificationMessage_Update {
            get {
                return ResourceManager.GetString("NotificationMessage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Header {
            get {
                return ResourceManager.GetString("Notifications_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Horizontal {
            get {
                return ResourceManager.GetString("Notifications_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Position {
            get {
                return ResourceManager.GetString("Notifications_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Preview {
            get {
                return ResourceManager.GetString("Notifications_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_ReactAll {
            get {
                return ResourceManager.GetString("Notifications_ReactAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Time {
            get {
                return ResourceManager.GetString("Notifications_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Notifications_Vertical {
            get {
                return ResourceManager.GetString("Notifications_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AddApp {
            get {
                return ResourceManager.GetString("Settings_AddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AddDevice {
            get {
                return ResourceManager.GetString("Settings_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AddHotkey {
            get {
                return ResourceManager.GetString("Settings_AddHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AlwaysTop {
            get {
                return ResourceManager.GetString("Settings_AlwaysTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AppsHotkeys {
            get {
                return ResourceManager.GetString("Settings_AppsHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_AppVolumeSync {
            get {
                return ResourceManager.GetString("Settings_AppVolumeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_BlockHotkeys {
            get {
                return ResourceManager.GetString("Settings_BlockHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DecreaseDevice {
            get {
                return ResourceManager.GetString("Settings_DecreaseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DecreaseHotkey {
            get {
                return ResourceManager.GetString("Settings_DecreaseHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DefaultDeviceHotkey {
            get {
                return ResourceManager.GetString("Settings_DefaultDeviceHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Device {
            get {
                return ResourceManager.GetString("Settings_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DeviceBottom {
            get {
                return ResourceManager.GetString("Settings_DeviceBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DeviceHotkeys {
            get {
                return ResourceManager.GetString("Settings_DeviceHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_DeviceIcon {
            get {
                return ResourceManager.GetString("Settings_DeviceIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Duplicates {
            get {
                return ResourceManager.GetString("Settings_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_ForegroundVolumeDown {
            get {
                return ResourceManager.GetString("Settings_ForegroundVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_ForegroundVolumeUp {
            get {
                return ResourceManager.GetString("Settings_ForegroundVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_HeaderHotkeys {
            get {
                return ResourceManager.GetString("Settings_HeaderHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_HeaderMisc {
            get {
                return ResourceManager.GetString("Settings_HeaderMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Hotkey {
            get {
                return ResourceManager.GetString("Settings_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_IncreaseDevice {
            get {
                return ResourceManager.GetString("Settings_IncreaseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_IncreaseHotkey {
            get {
                return ResourceManager.GetString("Settings_IncreaseHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Lang {
            get {
                return ResourceManager.GetString("Settings_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_LastPosition {
            get {
                return ResourceManager.GetString("Settings_LastPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_LaunchStartup {
            get {
                return ResourceManager.GetString("Settings_LaunchStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_MediaHotkeys {
            get {
                return ResourceManager.GetString("Settings_MediaHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_MediaReplace {
            get {
                return ResourceManager.GetString("Settings_MediaReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_MixerSettings {
            get {
                return ResourceManager.GetString("Settings_MixerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_MusicApp {
            get {
                return ResourceManager.GetString("Settings_MusicApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_MuteDevice {
            get {
                return ResourceManager.GetString("Settings_MuteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_OpenMixer {
            get {
                return ResourceManager.GetString("Settings_OpenMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Popup {
            get {
                return ResourceManager.GetString("Settings_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_PreventBalanceReset {
            get {
                return ResourceManager.GetString("Settings_PreventBalanceReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_RemoveApp {
            get {
                return ResourceManager.GetString("Settings_RemoveApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_RemoveDevice {
            get {
                return ResourceManager.GetString("Settings_RemoveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_RemoveHotkey {
            get {
                return ResourceManager.GetString("Settings_RemoveHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_SelectedScreen {
            get {
                return ResourceManager.GetString("Settings_SelectedScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_StartMenu {
            get {
                return ResourceManager.GetString("Settings_StartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_Tip {
            get {
                return ResourceManager.GetString("Settings_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_VolumeLimit {
            get {
                return ResourceManager.GetString("Settings_VolumeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_VolumeStep {
            get {
                return ResourceManager.GetString("Settings_VolumeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Settings_WindowBehavior {
            get {
                return ResourceManager.GetString("Settings_WindowBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Status_Muted {
            get {
                return ResourceManager.GetString("Status_Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TabHeader_Mixer {
            get {
                return ResourceManager.GetString("TabHeader_Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TabHeader_Settings {
            get {
                return ResourceManager.GetString("TabHeader_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrayMenu_ChangeDevice {
            get {
                return ResourceManager.GetString("TrayMenu_ChangeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrayMenu_SoundPanel {
            get {
                return ResourceManager.GetString("TrayMenu_SoundPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TrayMenu_SoundSettings {
            get {
                return ResourceManager.GetString("TrayMenu_SoundSettings", resourceCulture);
            }
        }
    }
}
